### ISSUE TITLE
How  to visualize predicted masks given layout?

### ISSUE THREAD

**Issue by 3288103265** [WillSuen/LostGANs#12]
Hi Sun,
Good job you have done! I am interested in how to visualize predicted masks. I have checked your code but not find it, can u help me :)

**Comment by WillSuen** [comment]
Hi, thanks for you comments. In order to visualize the mask, you just need to get the vector value of `stage_bbox` 
https://github.com/WillSuen/LostGANs/blob/70f5d4f6c1b0f90024faa1219a7c568b4cb6c767/model/resnet_generator_v2.py#L98
 and use `argmax` to get the label for visualization. Thanks,
