### ISSUE TITLE
FID score

### ISSUE THREAD

**Issue by wb-finalking** [WillSuen/LostGANs#13]
Hello! I am very interested in your work. And I use your pretrained model netGv2_coco128.pth for testing. But my metric scores(IS: 14.31, FID 30.71) are not match yours in paper (IS: 14.21, FID: 24.76). I want to know why there is a big difference between my FID score and yours.  I use the evaluate code mentioned in https://github.com/WillSuen/LostGANs/issues/3 and generate 5 images for each layout. 
Looking forward to your reply.

**Comment by WillSuen** [comment]
Hi thanks for your interests. How many images did you use for evaluate FID? I use all about 3000 images, so the FID is calculated over about 3k vs 15k. If still have the issue, could you please upload the generated images and let me have a check

**Comment by wb-finalking** [comment]
> Hi thanks for your interests. How many images did you use for evaluate FID? I use all about 3000 images, so the FID is calculated over about 3k vs 15k. If still have the issue, could you please upload the generated images and let me have a check

Sorry, its my fault to modify the code for image saving, which would result in information loss. When I use `misc.imsave` for image saving, FID score can reach to 24.8.
