### ISSUE TITLE
score

### ISSUE THREAD

**Issue by alibabadoufu** [WillSuen/LostGANs#3]
Hi, may I know where I could find the code for your reported inception score, FID, diversity score and classification accuracy?

**Comment by WillSuen** [comment]
Hi, Code for scores are taken from the official repo, [IS](https://github.com/openai/improved-gan/tree/master/inception_score) [FID](https://github.com/bioinf-jku/TTUR/blob/master/fid.py), [Diversity Score](https://github.com/richzhang/PerceptualSimilarity/blob/master/compute_dists_dirs.py).

For classification accuracy, we use this pytorch image classification [repo](https://github.com/hysts/pytorch_image_classification).
