### ISSUE TITLE
Code for LostGANs V2

### ISSUE THREAD

**Issue by PierfrancescoArdino** [WillSuen/LostGANs#4]
As said in the title, are you going to release the code for LostGANs V2 for the new version of the paper [Learning Layout and Style Reconfigurable GANs
for Controllable Image Synthesis](https://arxiv.org/abs/2003.11571)

**Comment by WillSuen** [comment]
Thanks for your interests. We are working on refining the code and will release it soon

**Comment by PierfrancescoArdino** [comment]
Is it possible to send me the code even if it is not refactored? We are really interested in some parts of your architecture

**Comment by WillSuen** [comment]
Can I have your email address?

**Comment by PierfrancescoArdino** [comment]
> Can I have your email address?

pierfrancesco.ardino@unitn.it Thank you so much
